/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clasesPrincipales.Entradas;
import clasesPrincipales.clientes;
import conexionSQLDB.DataBaseConexion;
import conexionSQLDB.entradaDB;
import java.io.*;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook; //New imports to read XLSX format
import org.apache.poi.xssf.usermodel.XSSFSheet; //New imports to read XLSX format
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.hssf.usermodel.HSSFFormulaEvaluator;
import org.apache.poi.xssf.usermodel.XSSFFormulaEvaluator; //New imports to formula evaluator in XLSX
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.poi.hssf.usermodel.HSSFRichTextString;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author CPU_SYS
 */
public class Entrada extends javax.swing.JFrame {

    ArrayList<Entradas> entrada;
    entradaDB db = new entradaDB();

    //excel obj = new excel();
    /**
     * Creates new form Entrada
     */
    public Entrada() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("CPU System Service S.A.S - ENTRADA");
        CargarCmbCliente();
        CargarCmbFacturas();
    }

    public void CargarCmbCliente() {
        try {
            Connection cnx = DataBaseConexion.getConnection();
            Statement st = cnx.createStatement();
            ResultSet rs = st.executeQuery("SELECT NOMBRECLIENTE FROM CLIENTES ORDER BY NOMBRECLIENTE ASC");
            while (rs.next()) {
                this.cmbClientes.addItem(rs.getString("nombrecliente"));
            }
        } catch (Exception e) {
        }
    }
    
    public void CargarCmbFacturas() {
        try {
            Connection cnx = DataBaseConexion.getConnection();
            Statement st = cnx.createStatement();
            ResultSet rs = st.executeQuery("SELECT ID_ENTRADA FROM ENTRADAS ORDER BY ID_ENTRADA DESC");
            while (rs.next()) {
                this.cmbFacturas.addItem(rs.getString("ID_ENTRADA"));
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        cmbClientes = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmbTarjetaDeRed = new javax.swing.JComboBox();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtCiudadCliente = new javax.swing.JTextField();
        txtElemento = new javax.swing.JTextField();
        txtPotencia = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtSerie = new javax.swing.JTextField();
        txtNitCliente = new javax.swing.JTextField();
        txtPersonaRemitente = new javax.swing.JTextField();
        txtEmpresa = new javax.swing.JTextField();
        txtDireccionCliente = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtContactoCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtCorreoCliente = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cmbGarantia = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        cmbParrilla = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        cmbBasesPlasticas = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        cmbEstadoCarcasa = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        cmbConectorOriginal = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaObservaciones = new javax.swing.JTextArea();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        txtFecha = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();
        btnDescartar = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        cmbFacturas = new javax.swing.JComboBox();
        btnBuscar1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnFacturas = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir1.setBackground(new java.awt.Color(51, 153, 255));
        btnSalir1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir1.setText("Salir");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Formato De Entrada");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 270, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 153));
        jLabel6.setText("FACTURAS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 70, 20));

        cmbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClientesActionPerformed(evt);
            }
        });
        getContentPane().add(cmbClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 260, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 150, 10));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Elemento");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Potencia");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 50, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Modelo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Serie");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Empresa remitente");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("NIT");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 30, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ciudad");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nombre");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 255, 153));
        jLabel16.setText("DATOS DEL CONTACTO");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 150, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Garantia");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 50, 20));

        cmbTarjetaDeRed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO", " " }));
        getContentPane().add(cmbTarjetaDeRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 60, 20));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 750, 10));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 310, 10));
        getContentPane().add(txtCiudadCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 150, -1));
        getContentPane().add(txtElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 150, -1));
        getContentPane().add(txtPotencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 150, -1));
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 180, -1));
        getContentPane().add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 150, -1));
        getContentPane().add(txtSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 150, -1));
        getContentPane().add(txtNitCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 150, -1));
        getContentPane().add(txtPersonaRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 170, -1));
        getContentPane().add(txtEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 170, -1));
        getContentPane().add(txtDireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 170, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Persona remitente");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Dirección");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        txtContactoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtContactoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 170, -1));

        txtTelefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 150, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Correo");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 40, 20));

        txtCorreoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorreoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 180, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Telefono");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 50, 20));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 310, 10));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 255, 153));
        jLabel22.setText("REVISIÓN DE LA MAQUINA");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 10, 90));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Estado Carcasa");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, 20));
        getContentPane().add(txtMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 700, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Marca");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 40, 20));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 255, 153));
        jLabel25.setText("FECHA");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 40, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Motivo");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 20));

        cmbGarantia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO", " " }));
        cmbGarantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGarantiaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 60, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Parrilla");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, 20));

        cmbParrilla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO", " " }));
        getContentPane().add(cmbParrilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 60, 20));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Bases Plasticas");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 90, 20));

        cmbBasesPlasticas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO", " " }));
        getContentPane().add(cmbBasesPlasticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 60, 20));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Conector original");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, 20));

        cmbEstadoCarcasa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buen Estado", "Mal Estado", " ", " " }));
        getContentPane().add(cmbEstadoCarcasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 110, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Tarjeta de red");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 20));

        cmbConectorOriginal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO", " " }));
        getContentPane().add(cmbConectorOriginal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 60, 20));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Observaciones");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, 20));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, 10));

        areaObservaciones.setColumns(20);
        areaObservaciones.setRows(5);
        jScrollPane1.setViewportView(areaObservaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 520, 80));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 100, 10));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 260, 10));

        btnGuardar.setBackground(new java.awt.Color(153, 204, 255));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 80, 30));

        btnVolver.setBackground(new java.awt.Color(51, 153, 255));
        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, -1, -1));

        btnPDF.setBackground(new java.awt.Color(153, 204, 255));
        btnPDF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPDF.setText("PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });
        getContentPane().add(btnPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 80, 30));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 190, -1));

        btnBuscar.setBackground(new java.awt.Color(153, 204, 255));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 70, 20));

        btnDescartar.setBackground(new java.awt.Color(153, 204, 255));
        btnDescartar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDescartar.setText("DESCARTAR");
        btnDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 100, 30));

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 10, 90));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 100, 10));

        cmbFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFacturasActionPerformed(evt);
            }
        });
        getContentPane().add(cmbFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 160, -1));

        btnBuscar1.setBackground(new java.awt.Color(153, 204, 255));
        btnBuscar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 153));
        jLabel7.setText("CLIENTES");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, 20));

        btnFacturas.setBackground(new java.awt.Color(153, 255, 153));
        btnFacturas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFacturas.setText("FACTURAS");
        btnFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturasActionPerformed(evt);
            }
        });
        getContentPane().add(btnFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 250, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Entrada.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed

        System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void txtCorreoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoClienteActionPerformed

    private void cmbGarantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGarantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGarantiaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed

        Formatos_Admin obj = new Formatos_Admin();
        obj.setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed

        /*
         String fecha = txtFecha.getDateFormatString();
         String elemento = txtElemento.getText();
         String potencia = txtPotencia.getText();
         String marca = txtMarca.getText();
         String modelo = txtModelo.getText();
         String serie = txtSerie.getText();
         String nit = txtNit.getText();
         String empRemite = txtEmpresaRemitente.getText();
         String ciudad = txtCiudad.getText();
         String garantia = cmbGarantia.getSelectedItem().toString();
         String direccion = txtDireccion.getText();
         String preRemite = txtPersonaRemitente.getText();
         String nombreContacto = txtNombreContacto.getText();
         String telefonoContacto = txtTelefonoContacto.getText();
         String correoContacto = txtCorreoContacto.getText();
         String motivo = txtMotivo.getText();
         String tarjetaDeRed = cmbTarjetaDeRed.getSelectedItem().toString();
         String parrilla = cmbParrilla.getSelectedItem().toString();
         String basesPals = cmbBasesPlasticas.getSelectedItem().toString();
         String estadoCarcasa = cmbEstadoCarcasa.getSelectedItem().toString();
         String conectorOrig = cmbConectorOriginal.getSelectedItem().toString();
         String observaciones = areaObservaciones.getText();
        
         */
        JFileChooser selector = new JFileChooser();
        String directorio = "";
        String extension = "";
        boolean seleccion = false;

        int resultado = selector.showOpenDialog(null);

        switch (resultado) {
            case JFileChooser.APPROVE_OPTION:
                directorio = selector.getSelectedFile().getPath();

                int i = directorio.lastIndexOf('.');
                if (i >= 0) {
                    extension = directorio.substring(i + 1);
                }

                seleccion = true;

                JOptionPane.showMessageDialog(null, "Seleccionaste " + directorio);
                break;
            case JFileChooser.CANCEL_OPTION:
                seleccion = false;
                JOptionPane.showMessageDialog(null, "No seleccionaste nada.");
                break;
            case JFileChooser.ERROR_OPTION:
                seleccion = false;
                JOptionPane.showMessageDialog(null, "Ocurrio un Error.");
                break;
            default:
                break;
        }

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        if (seleccion) {

            switch (extension) {
                case "xls": {
                    FileInputStream entrada = null;
                    try {
                        //Leer el archivo de Excel XLS
                        entrada = new FileInputStream(new File(directorio));
                        //Acceso al libro de trabajo
                        HSSFWorkbook xls = new HSSFWorkbook(entrada);
                        //Acceso a la hoja de trabajo
                        HSSFSheet hoja = xls.getSheetAt(0);
                        //Declaracion de fila y celda
                        Row fila = null;
                        Cell celda = null;
                        try {
                            //Asignando a valores a celdas con valores
                            fila = hoja.getRow(13);
                            celda = fila.getCell(6);
                            HSSFRichTextString fecha = new HSSFRichTextString(txtFecha.getDateFormatString());
                            celda.setCellValue(fecha);

                            fila = hoja.getRow(4);
                            celda = fila.getCell(1);
                            HSSFRichTextString elemento = new HSSFRichTextString(txtElemento.getText());
                            celda.setCellValue(elemento);

                            fila = hoja.getRow(4);
                            celda = fila.getCell(4);
                            HSSFRichTextString potencia = new HSSFRichTextString(txtPotencia.getText());
                            celda.setCellValue(potencia);

                            /*
                             fila = hoja.getRow(1);

                             celda = fila.getCell(0);
                             celda.setCellValue(valor2);
                             celda = fila.getCell(1);
                             celda.setCellValue(valor4);
                             */
                        } catch (NullPointerException NPE) {
                            //En caso de que las celdas esten vacias hay que crearlas

                            fila = hoja.createRow(13);
                            celda = fila.createCell(6);
                            HSSFRichTextString fecha = new HSSFRichTextString(txtFecha.getDateFormatString());
                            celda.setCellValue(fecha);

                            fila = hoja.createRow(4);
                            celda = fila.createCell(1);
                            HSSFRichTextString elemento = new HSSFRichTextString(txtElemento.getText());
                            celda.setCellValue(elemento);

                            fila = hoja.createRow(4);
                            celda = fila.createCell(4);
                            HSSFRichTextString potencia = new HSSFRichTextString(txtPotencia.getText());
                            celda.setCellValue(potencia);

                        }       //Evaluando formulas de todo el libro de excel
                        HSSFFormulaEvaluator.evaluateAllFormulaCells(xls);
                        //Cerrando archivo
                        entrada.close();
                        //Abriendo archivo para escritura
                        FileOutputStream salida = new FileOutputStream(new File(directorio));
                        //write changes
                        xls.write(salida);
                        //close the stream
                        salida.close();
                        break;
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
                    } finally {
                        try {
                            entrada.close();
                        } catch (IOException ex) {
                            Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }       //Evaluando formulas de todo el libro de excel
                }
                case "xlsx": {
                    FileOutputStream salida = null;
                    try {
                        //Leer el archivo de Excel XLSX
                        FileInputStream entrada = null;
                        try {
                            entrada = new FileInputStream(new File(directorio));
                        } catch (FileNotFoundException ex) {
                            Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        //Acceso al libro de trabajo
                        XSSFWorkbook xlsx = null;
                        try {
                            xlsx = new XSSFWorkbook(entrada);
                        } catch (IOException ex) {
                            Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        //Acceso a la hoja de trabajo
                        XSSFSheet hoja = xlsx.getSheetAt(0);
                        //Declaracion de fila y celda
                        Row fila = null;
                        Cell celda = null;
                        try {
                            //Asignando a valores a celdas con valores
                            fila = hoja.getRow(13);
                            celda = fila.getCell(6);
                            HSSFRichTextString fecha = new HSSFRichTextString(txtFecha.getDateFormatString());
                            celda.setCellValue(fecha);

                            fila = hoja.getRow(4);
                            celda = fila.getCell(1);
                            HSSFRichTextString elemento = new HSSFRichTextString(txtElemento.getText());
                            celda.setCellValue(elemento);

                            fila = hoja.getRow(4);
                            celda = fila.getCell(4);
                            HSSFRichTextString potencia = new HSSFRichTextString(txtPotencia.getText());
                            celda.setCellValue(potencia);

                        } catch (NullPointerException NPE) {
                            //En caso de que las celdas esten vacias hay que crearlas

                            fila = hoja.createRow(13);
                            celda = fila.createCell(6);
                            HSSFRichTextString fecha = new HSSFRichTextString(txtFecha.getDateFormatString());
                            celda.setCellValue(fecha);

                            fila = hoja.createRow(4);
                            celda = fila.createCell(1);
                            HSSFRichTextString elemento = new HSSFRichTextString(txtElemento.getText());
                            celda.setCellValue(elemento);

                            fila = hoja.createRow(4);
                            celda = fila.createCell(4);
                            HSSFRichTextString potencia = new HSSFRichTextString(txtPotencia.getText());
                            celda.setCellValue(potencia);

                        }       //Evaluando formulas de todo el libro de excel
                        XSSFFormulaEvaluator.evaluateAllFormulaCells(xlsx);
                        //Cerrando la entrada archivo
                        entrada.close();
                        //Abriendo archivo para escritura
                        salida = new FileOutputStream(new File(directorio));
                        //write changes
                        xlsx.write(salida);
                        //close the stream
                        salida.close();
                        break;
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
                    } finally {
                        try {
                            salida.close();
                        } catch (IOException ex) {
                            Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnPDFActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        try {

            String guardar = cmbClientes.getSelectedItem().toString();
            Connection cnx = DataBaseConexion.getConnection();
            Statement st = cnx.createStatement();
            PreparedStatement pst = cnx.prepareStatement("Select * from Clientes where NOMBRECLIENTE = ?");
            pst.setString(1, guardar);
            //pst.setString(1, CMBID.getName());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {

                txtNitCliente.setText(rs.getString("nitcliente").trim());
                txtEmpresa.setText(rs.getString("nombrecliente").trim());
                txtTelefonoCliente.setText(rs.getString("telefonocliente").trim());
                txtDireccionCliente.setText(rs.getString("direccioncliente").trim());
                txtCiudadCliente.setText(rs.getString("ciudadcliente").trim());
                txtCorreoCliente.setText(rs.getString("correocliente").trim());
                txtContactoCliente.setText(rs.getString("nombrecontacto").trim());
                txtPersonaRemitente.setText(rs.getString("nombrecontacto").trim());

                //pst.setString(1, CMBID.getName());
                //String guardar = txtBuscar.getText();
            } else {
                JOptionPane.showMessageDialog(null, "No existe el usuario");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cmbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbClientesActionPerformed

    private void txtContactoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactoClienteActionPerformed

    private void btnDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescartarActionPerformed

        txtNitCliente.setText("");
        txtEmpresa.setText("");
        txtTelefonoCliente.setText("");
        txtDireccionCliente.setText("");
        txtCiudadCliente.setText("");
        txtCorreoCliente.setText("");
        txtContactoCliente.setText("");
        txtElemento.setText("");
        txtPotencia.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtSerie.setText("");
        txtMotivo.setText("");
        areaObservaciones.setText("");
        txtPersonaRemitente.setText("");
        txtFecha.setDateFormatString("");
        txtElemento.requestFocus();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDescartarActionPerformed

    private void txtTelefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoClienteActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        Entradas en = new Entradas();
        
        String formato = txtFecha.getDateFormatString();
        Date date = txtFecha.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat(formato);
        String dato = String.valueOf(sdf.format(date));
        
        en.setFecha(dato);
        en.setElemento(txtElemento.getText().toUpperCase());
        en.setPotencia(txtPotencia.getText().toUpperCase());
        en.setMarca(txtMarca.getText().toUpperCase());
        en.setModelo(txtModelo.getText().toUpperCase());
        en.setSerie(txtSerie.getText().toUpperCase());
        en.setEmpresa(txtEmpresa.getText().toUpperCase());
        en.setNit(txtNitCliente.getText().toUpperCase());
        en.setPersona_remite(txtPersonaRemitente.getText().toUpperCase());
        en.setCiudad(txtCiudadCliente.getText().toUpperCase());
        en.setDireccion(txtDireccionCliente.getText().toUpperCase());
        en.setNombre_contacto(txtContactoCliente.getText().toUpperCase());
        en.setTelefono_contacto(txtTelefonoCliente.getText().toUpperCase());
        en.setCorreo(txtCorreoCliente.getText().toUpperCase());
        en.setMotivo(txtMotivo.getText().toUpperCase());
        en.setTarjeta_red(cmbTarjetaDeRed.getSelectedItem().toString().toUpperCase());
        en.setParrilla(cmbParrilla.getSelectedItem().toString().toUpperCase());
        en.setBases_plasticas(cmbBasesPlasticas.getSelectedItem().toString().toUpperCase());
        en.setConector_origi(cmbConectorOriginal.getSelectedItem().toString().toUpperCase());
        en.setGarantia(cmbGarantia.getSelectedItem().toString().toUpperCase());
        en.setEstado_carcasa(cmbEstadoCarcasa.getSelectedItem().toString().toUpperCase());
        en.setObservaciones(areaObservaciones.getText().toUpperCase());

        if (txtFecha.getDateFormatString().equals("") || txtElemento.getText().equals("") || txtPotencia.getText().equals("") || txtMarca.getText().equals("") || txtModelo.getText().equals("") || txtSerie.getText().equals("") || txtEmpresa.getText().equals("")
                || txtNitCliente.getText().equals("") || txtPersonaRemitente.getText().equals("") || txtCiudadCliente.getText().equals("") || txtDireccionCliente.getText().equals("") || txtContactoCliente.getText().equals("") || txtTelefonoCliente.getText().equals("") || txtCorreoCliente.getText().equals("") || txtMotivo.getText().equals("") || areaObservaciones.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos", "", JOptionPane.INFORMATION_MESSAGE);
        } else {

            try {
                db.insertarEntrada(en);
                JOptionPane.showMessageDialog(this, "Factura guardada exitosamente", "", JOptionPane.INFORMATION_MESSAGE);

                txtNitCliente.setText("");
                txtEmpresa.setText("");
                txtTelefonoCliente.setText("");
                txtDireccionCliente.setText("");
                txtCiudadCliente.setText("");
                txtCorreoCliente.setText("");
                txtContactoCliente.setText("");
                txtElemento.setText("");
                txtPotencia.setText("");
                txtMarca.setText("");
                txtModelo.setText("");
                txtSerie.setText("");
                txtMotivo.setText("");
                areaObservaciones.setText("");
                txtPersonaRemitente.setText("");
                txtFecha.setDateFormatString("");
                this.cmbClientes.removeAllItems();
                this.cmbFacturas.removeAllItems();
                CargarCmbCliente();
                CargarCmbFacturas();
                txtElemento.requestFocus();
            } catch (Exception e) {
                System.err.println("error" + e);
            }

        }

        /*

         Formatos_Oper obj = new Formatos_Oper();

         if (seleccion) {
         FileInputStream entrada = null;
         try {
         //Leer el archivo de Excel XLS
         entrada = new FileInputStream(new File(directorio));
         //Acceso al libro de trabajo
         HSSFWorkbook xls = new HSSFWorkbook(entrada);
         //Acceso a la hoja de trabajo
         HSSFSheet hoja = xls.getSheetAt(0);
         //Declaracion de fila y celda
         Row fila = null;
         Cell celda = null;
         try {
         //Asignando a valores a celdas con valores
         fila = hoja.getRow(13);
         celda = fila.getCell(6);
         HSSFRichTextString fecha = new HSSFRichTextString(txtFecha.getDateFormatString());
         celda.setCellValue(fecha);

         fila = hoja.getRow(4);
         celda = fila.getCell(1);
         HSSFRichTextString elemento = new HSSFRichTextString(txtElemento.getText());
         celda.setCellValue(elemento);

         fila = hoja.getRow(4);
         celda = fila.getCell(4);
         HSSFRichTextString potencia = new HSSFRichTextString(txtPotencia.getText());
         celda.setCellValue(potencia);

         fila = hoja.getRow(1);

         celda = fila.getCell(0);
         celda.setCellValue(valor2);
         celda = fila.getCell(1);
         celda.setCellValue(valor4);

         } catch (NullPointerException NPE) {
         //En caso de que las celdas esten vacias hay que crearlas

         fila = hoja.createRow(13);
         celda = fila.createCell(6);
         HSSFRichTextString fecha = new HSSFRichTextString(txtFecha.getDateFormatString());
         celda.setCellValue(fecha);

         fila = hoja.createRow(4);
         celda = fila.createCell(1);
         HSSFRichTextString elemento = new HSSFRichTextString(txtElemento.getText());
         celda.setCellValue(elemento);

         fila = hoja.createRow(4);
         celda = fila.createCell(4);
         HSSFRichTextString potencia = new HSSFRichTextString(txtPotencia.getText());
         celda.setCellValue(potencia);

         }       //Evaluando formulas de todo el libro de excel
         HSSFFormulaEvaluator.evaluateAllFormulaCells(xls);
         //Cerrando archivo
         entrada.close();
         //Abriendo archivo para escritura
         FileOutputStream salida = new FileOutputStream(new File(directorio));
         //write changes
         xls.write(salida);
         //close the stream
         salida.close();
         } catch (FileNotFoundException ex) {
         Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
         Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
         } finally {
         try {
         entrada.close();
         } catch (IOException ex) {
         Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
         }
         }       //Evaluando formulas de todo el libro de excel
         }

         */
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cmbFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFacturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFacturasActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed

        //(FECHA, ELEMENTO, POTENCIA, MARCA, MODELO, SERIE, EMPRESA, NIT, PERSONA_REMITE, CIUDAD, DIRECCION, NOMBRE_CONTACTO, TELEFONO_CONTACTO, CORREO, MOTIVO, TARJETA_RED, PARRILLA, BASES_PLASTICAS, CONECTOR_ORIGI, GARANTIA, ESTADO_CARCASA, OBSERVACIONES)
        
        try {

            String guardar = cmbFacturas.getSelectedItem().toString();
            Connection cnx = DataBaseConexion.getConnection();
            Statement st = cnx.createStatement();
            PreparedStatement pst = cnx.prepareStatement("Select * from ENTRADAS where ID_ENTRADA = ?");
            pst.setString(1, guardar);
            //pst.setString(1, CMBID.getName());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {

                txtFecha.setToolTipText(rs.getString("FECHA").trim());
                txtElemento.setText(rs.getString("ELEMENTO").trim());
                txtPotencia.setText(rs.getString("POTENCIA").trim());
                txtMarca.setText(rs.getString("MARCA").trim());
                txtModelo.setText(rs.getString("MODELO").trim());
                txtSerie.setText(rs.getString("SERIE").trim());
                txtEmpresa.setText(rs.getString("EMPRESA").trim());
                txtNitCliente.setText(rs.getString("NIT").trim());
                txtPersonaRemitente.setText(rs.getString("PERSONA_REMITE").trim());
                txtCiudadCliente.setText(rs.getString("CIUDAD").trim());
                txtDireccionCliente.setText(rs.getString("DIRECCION").trim());
                txtContactoCliente.setText(rs.getString("NOMBRE_CONTACTO").trim());
                txtTelefonoCliente.setText(rs.getString("TELEFONO_CONTACTO").trim());
                txtCorreoCliente.setText(rs.getString("CORREO").trim());
                txtMotivo.setText(rs.getString("MOTIVO").trim());
                
                txtCorreoCliente.setText(rs.getString("correocliente").trim());
                txtContactoCliente.setText(rs.getString("nombrecontacto").trim());
                txtTelefonoCliente.setText(rs.getString("telefonocliente").trim());
                txtDireccionCliente.setText(rs.getString("direccioncliente").trim());
                txtCiudadCliente.setText(rs.getString("ciudadcliente").trim());
                txtCorreoCliente.setText(rs.getString("correocliente").trim());
                txtContactoCliente.setText(rs.getString("nombrecontacto").trim());

                //pst.setString(1, CMBID.getName());
                //String guardar = txtBuscar.getText();
            } else {
                JOptionPane.showMessageDialog(null, "No existe el usuario");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturasActionPerformed

        Facturas_Entrada obj = new Facturas_Entrada();
        obj.setVisible(true);
        dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnFacturasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaObservaciones;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnFacturas;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox cmbBasesPlasticas;
    private javax.swing.JComboBox cmbClientes;
    private javax.swing.JComboBox cmbConectorOriginal;
    private javax.swing.JComboBox cmbEstadoCarcasa;
    private javax.swing.JComboBox cmbFacturas;
    private javax.swing.JComboBox cmbGarantia;
    private javax.swing.JComboBox cmbParrilla;
    private javax.swing.JComboBox cmbTarjetaDeRed;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField txtCiudadCliente;
    private javax.swing.JTextField txtContactoCliente;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtElemento;
    private javax.swing.JTextField txtEmpresa;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtNitCliente;
    private javax.swing.JTextField txtPersonaRemitente;
    private javax.swing.JTextField txtPotencia;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
